--- 
document:
  name: Linee guida nazionali per la valorizzazione del patrimonio informativo pubblico
  description: |
    Questo documento rappresenta le linee guida per la valorizzazione del
    patrimonio informativo pubblico per l’anno 2017 pubblicate dall’Agenzia
    per l’Italia Digitale.
  tags:
    - linee guida
